name: 'Ice install'
description: 'Install Ice 3.6 on ubuntu 24.04'
inputs:
  java-version:
    description: 'Version of Java to use'
    required: false
    default: 11
  java-distribution:
    description: 'The Java distribution to install'
    required: false
    default: 'temurin'
  python-version:
    description: 'Version of Python to use'
    required: false
    default: '3.12'


runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - name: Install slice2java
      run: |
        sudo apt-get install -y libmcpp-dev
        wget -q https://github.com/glencoesoftware/zeroc-ice-ubuntu2404-x86_64/releases/download/20240619/Ice-3.6.5-ubuntu2404-x86_64.tar.gz
        tar xf Ice-3.6.5-ubuntu2404-x86_64.tar.gz
        mv Ice-3.6.5 /opt/ice-3.6.5
        rm Ice-3.6.5-ubuntu2404-x86_64.tar.gz
        echo "/opt/ice-3.6.5/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Ice Python binding
      if: ${{ inputs.python-version == '3.10' }}
      shell: bash
      run: |
        pip install https://github.com/glencoesoftware/zeroc-ice-py-linux-x86_64/releases/download/20240202/zeroc_ice-3.6.5-cp310-cp310-manylinux_2_28_x86_64.whl
    - name: Install Ice Python binding
      if: ${{ inputs.python-version == '3.11' }}
      shell: bash
      run: |
        pip install https://github.com/glencoesoftware/zeroc-ice-py-linux-x86_64/releases/download/20240202/zeroc_ice-3.6.5-cp311-cp311-manylinux_2_28_x86_64.whl
    - name: Install Ice Python binding
      if: ${{ inputs.python-version == '3.12' }}
      shell: bash
      run: |
        pip install https://github.com/glencoesoftware/zeroc-ice-py-linux-x86_64/releases/download/20240202/zeroc_ice-3.6.5-cp312-cp312-manylinux_2_28_x86_64.whl
        
     
